In [1]:
# pip install --ignore-installed --upgrade tensorflow 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

2023-11-11 15:52:36.765622: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [30]:
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)

## Part 1

In [3]:
X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)       #(price in 1000s of dollars)

- If you don't specify anything, no activation is applied (ie. "linear" activation: `a(x) = x`).

In [4]:
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )

In [5]:
linear_layer.get_weights() # There are no weights as the weights are not yet instantiated.

[]

In [6]:
# Instantiation of the weights. 
## Note: The input to the layer must be 2-D, so we need to reshape it.

a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[-1.0194235]], shape=(1, 1), dtype=float32)


- The result is a `tensor (another name for an array)` with a shape of (1,1) or one entry.

In [7]:
# These weights are randomly initialized to small numbers and the bias defaults to being initialized to zero.

w, b= linear_layer.get_weights()
print(f"w = {w}, b={b}")

w = [[-1.0194235]], b=[0.]


In [8]:
set_w = np.array([[200]])
set_b = np.array([100])

# set_weights takes a list of numpy arrays
linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [9]:
a1 = linear_layer(X_train[0].reshape(1,1)) #This is different as we set weights above 
print(a1)
alin = np.dot(set_w,X_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


### Logistic Regression

In [10]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [11]:
pos = Y_train == 1
neg = Y_train == 0
X_train[pos]

array([3., 4., 5.], dtype=float32)

- We can implement a 'logistic neuron' by adding a sigmoid activation. 
- Tensorflow is most often used to `create multi-layer models`. The `Sequential model` is a convenient means of constructing these models.

In [12]:
model = Sequential(
    [
        tf.keras.layers.Dense(units=1, input_dim=1,  activation = 'sigmoid', name='L1')
    ]
)

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
logistic_layer = model.get_layer('L1')
w,b = logistic_layer.get_weights()
print(w,b)
print(w.shape,b.shape)

[[1.6137158]] [0.]
(1, 1) (1,)


In [15]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
# set_weights takes a list of numpy arrays
logistic_layer.set_weights([set_w, set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [16]:
a1 = model.predict(X_train[0].reshape(1,1))
print(a1)

1/1 [==============================] - 0s 92ms/step
[[0.01098694]]


In [17]:
test = np.array([200.0, 17.0]) # This is just a 1D array or vector with no row/column
test.shape

(2,)

In [18]:
test = np.array([[200.0, 17.0]])
test.shape

(1, 2)

### Using Keras Normalisation Layer (Normalise features)

In [19]:
print(tf.__version__)

2.14.0


In [20]:
# pip install --upgrade tensorflow

- The Normalisation later is not a layer in the model.
- 'adapt' the data. This learns the mean and variance of the data set and saves the values internally.
- It is important to apply normalization to any future data that utilizes the learned model.

In [21]:
norm_l = tf.keras.layers.Normalization(axis=-1)

In [22]:
norm_l

In [24]:
norm_l.adapt(X_train)  # learns mean, variance

In [28]:
# X_train

In [26]:
Xn = norm_l(X_train)
Xn

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[-1.46385],
       [-0.87831],
       [-0.29277],
       [ 0.29277],
       [ 0.87831],
       [ 1.46385]], dtype=float32)>

In [29]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        tf.keras.Input(shape=(2,)), # specifies the expected shape of the input.
        Dense(3, activation='sigmoid', name = 'layer1'),
        Dense(1, activation='sigmoid', name = 'layer2')
     ]
)

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13 (52.00 Byte)
Trainable params: 13 (52.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()

print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"\nW2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

- The `model.compile` statement defines a loss function and specifies a compile optimization.
- The `model.fit` statement runs gradient descent and fits the weights to the data.

In [ ]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    Xt,Yt,            
    epochs=10,
)

In [ ]:
X_test = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example
X_testn = norm_l(X_test)

predictions = model.predict(X_testn)
print("predictions = \n", predictions)

### Forward Propagation

In [ ]:
# Define the activation function
def sigmoid(z):
    
    return 1/(1+np.exp(-z))

g = sigmoid

def my_dense(a_in, W, b):
    """
    Computes dense layer
    Args:
      a_in (ndarray (n, )) : Data, 1 example 
      W    (ndarray (n,j)) : Weight matrix, n features per unit, j units
      b    (ndarray (j, )) : bias vector, j units  
    Returns
      a_out (ndarray (j,))  : j units|
    """
    units = W.shape[1]
    a_out = np.zeros(units)
    
    for j in range(units):               
        w = W[:,j]                                    
        z = np.dot(w, a_in) + b[j]         
        a_out[j] = g(z)  
    
#     Z = a_in@W + b
#     a_out = g(Z)
        
    return(a_out)

def my_sequential(x, W1, b1, W2, b2):
    a1 = my_dense(x,  W1, b1)
    a2 = my_dense(a1, W2, b2)
    
    return(a2)

def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = my_sequential(X[i], W1, b1, W2, b2)
        
    return(p)

In [ ]:
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

In [ ]:
X_tst = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example
X_tstn = norm_l(X_tst)  # remember to normalize
predictions = my_predict(X_tstn, W1_tmp, b1_tmp, W2_tmp, b2_tmp)

In [ ]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

## Part 2

In [31]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU
from tensorflow.keras.activations import linear, relu, sigmoid

In [32]:
def my_softmax(z):
    ez = np.exp(z)              #element-wise exponenial
    sm = ez/np.sum(ez)
    return(sm)

In [33]:
from sklearn.datasets import make_blobs

# make sample cluster dataset
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [34]:
model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001), #Adam algo can adjust learning rate automatically
)

model.fit(
    X_train,y_train,
    epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 3ms/step - loss: 0.8178
Epoch 2/10
63/63 [==============================] - 0s 3ms/step - loss: 0.3559
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1621
Epoch 4/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0869
Epoch 5/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0611
Epoch 6/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0496
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0434
Epoch 8/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0394
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0357
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0331


In [35]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 2ms/step
[[3.2728643e-03 7.7583659e-03 9.7527909e-01 1.3689701e-02]
 [9.9530345e-01 4.6304273e-03 1.0635924e-05 5.5508030e-05]]
largest value 0.99999946 smallest value 9.027318e-09


In [36]:
preferred_model = Sequential(
    [ 
        Dense(25, activation = 'relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        Dense(15, activation = 'relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 3ms/step - loss: 0.8344
Epoch 2/10
63/63 [==============================] - 0s 5ms/step - loss: 0.2614
Epoch 3/10
63/63 [==============================] - 0s 3ms/step - loss: 0.1213
Epoch 4/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0801
Epoch 5/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0632
Epoch 6/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0534
Epoch 7/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0473
Epoch 8/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0431
Epoch 9/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0394
Epoch 10/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0367


In [39]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"\ntwo example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

63/63 [==============================] - 0s 2ms/step
two example output vectors:
 [[-4.4399056  -1.4222862   4.334922    0.06531854]
 [ 0.7538949  -4.480299   -9.018383   -7.9122405 ]]
largest value 12.033584 smallest value -13.171318

two example output vectors:
 [[1.5194653e-04 3.1061796e-03 9.8299241e-01 1.3749441e-02]
 [9.9447024e-01 5.3016413e-03 5.6695091e-05 1.7137082e-04]]
largest value 0.9999997 smallest value 8.827092e-11


Tensorflow has two potential formats for target values and the selection of the loss defines which is expected.

- `SparseCategorialCrossentropy`: expects the target to be an integer corresponding to the index. For example, if there are 10 potential target values, y would be between 0 and 9.
- `CategoricalCrossEntropy`: Expects the target value of an example to be one-hot encoded where the value at the target index is 1 while the other N-1 entries are zero. An example with 10 potential target values, where the target is 2 would be [0,0,1,0,0,0,0,0,0,0].

### Running Diagnostics

In [40]:
# for building linear regression models and preparing data
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
# Load the dataset from the text file
data = np.loadtxt('./data/data_w3_ex1.csv', delimiter=',')

# Split the inputs and outputs into separate arrays
x = data[:,0]
y = data[:,1]

# Convert 1-D arrays into 2-D because the commands later will require it
x = np.expand_dims(x, axis=1)
#x = data[:,0].reshape(-1,1)
y = np.expand_dims(y, axis=1)

- Split the dataset into training, cross validation, and test sets


In [ ]:
# Get 60% of the dataset as the training set. Put the remaining 40% in temporary variables: x_ and y_.
x_train, x_, y_train, y_ = train_test_split(x, y, test_size=0.40, random_state=1)

# Split the 40% subset above into two: one half for cross validation and the other for the test set
x_cv, x_test, y_cv, y_test = train_test_split(x_, y_, test_size=0.50, random_state=1)

# Delete temporary variables
del x_, y_

- Feature scaling

In [ ]:
# Initialize the class
scaler_linear = StandardScaler() 

# Compute the mean and standard deviation of the training set then transform it
X_train_scaled = scaler_linear.fit_transform(x_train)

In [ ]:
# Initialize the class
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train_scaled, y_train )

# Feed the scaled training set and get the predictions
yhat = linear_model.predict(X_train_scaled)

# Use scikit-learn's utility function and divide by 2
print(f"training MSE (using sklearn function): {mean_squared_error(y_train, yhat) / 2}")

# for-loop implementation
total_squared_error = 0

for i in range(len(yhat)):
    squared_error_i  = (yhat[i] - y_train[i])**2
    total_squared_error += squared_error_i                                              

mse = total_squared_error / (2*len(yhat))

print(f"training MSE (for-loop implementation): {mse.squeeze()}")

In [ ]:
# Scale the cross validation set using the mean and standard deviation of the training set
X_cv_scaled = scaler_linear.transform(x_cv)

print(f"Mean used to scale the CV set: {scaler_linear.mean_.squeeze():.2f}")
print(f"Standard deviation used to scale the CV set: {scaler_linear.scale_.squeeze():.2f}")

# Feed the scaled cross validation set
yhat = linear_model.predict(X_cv_scaled)

# Use scikit-learn's utility function and divide by 2
print(f"Cross validation MSE: {mean_squared_error(y_cv, yhat) / 2}")

- Generate the polynomial features from your training set

In [ ]:
# Instantiate the class to make polynomial features
poly = PolynomialFeatures(degree=2, include_bias=False)

# Compute the number of features and transform the training set
X_train_mapped = poly.fit_transform(x_train)

In [ ]:
# Instantiate the class
scaler_poly = StandardScaler()

# Compute the mean and standard deviation of the training set then transform it
X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)

# Preview the first 5 elements of the scaled training set.
print(X_train_mapped_scaled[:5])

In [ ]:
# Initialize the class
model = LinearRegression()

# Train the model
model.fit(X_train_mapped_scaled, y_train )

# Compute the training MSE
yhat = model.predict(X_train_mapped_scaled)
print(f"Training MSE: {mean_squared_error(y_train, yhat) / 2}")

# Add the polynomial features to the cross validation set
X_cv_mapped = poly.transform(x_cv)

# Scale the cross validation set using the mean and standard deviation of the training set
X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)

# Compute the cross validation MSE
yhat = model.predict(X_cv_mapped_scaled)
print(f"Cross validation MSE: {mean_squared_error(y_cv, yhat) / 2}")

In [ ]:
# Initialize lists containing the lists, models, and scalers
train_mses = []
cv_mses = []
models = []
scalers = []

# Loop over 10 times. Each adding one more degree of polynomial higher than the last.
for degree in range(1,11):
    
    # Add polynomial features to the training set
    poly = PolynomialFeatures(degree, include_bias=False)
    X_train_mapped = poly.fit_transform(x_train)
    
    # Scale the training set
    scaler_poly = StandardScaler()
    X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)
    scalers.append(scaler_poly)
    
    # Create and train the model
    model = LinearRegression()
    model.fit(X_train_mapped_scaled, y_train )
    models.append(model)
    
    # Compute the training MSE
    yhat = model.predict(X_train_mapped_scaled)
    train_mse = mean_squared_error(y_train, yhat) / 2
    train_mses.append(train_mse)
    
    # Add polynomial features and scale the cross validation set
    poly = PolynomialFeatures(degree, include_bias=False)
    X_cv_mapped = poly.fit_transform(x_cv)
    X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)
    
    # Compute the cross validation MSE
    yhat = model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    cv_mses.append(cv_mse)
    

In [ ]:
# Get the model with the lowest CV MSE (add 1 because list indices start at 0)
# This also corresponds to the degree of the polynomial added
degree = np.argmin(cv_mses) + 1
print(f"Lowest CV MSE is found in the model with degree={degree}")

- Sample codes for NN

In [ ]:
# Initialize lists that will contain the errors for each model
nn_train_mses = []
nn_cv_mses = []

# Build the models 
nn_models = utils.build_models() #Build myself (or see utils.py)

# Loop over the the models
for model in nn_models:
    
    # Setup the loss and optimizer
    model.compile(
    loss='mse',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
    )

    print(f"Training {model.name}...")
    
    # Train the model
    model.fit(
        X_train_mapped_scaled, y_train,
        epochs=300,
        verbose=0
    )
    
    print("Done!\n")

    
    # Record the training MSEs
    yhat = model.predict(X_train_mapped_scaled)
    train_mse = mean_squared_error(y_train, yhat) / 2
    nn_train_mses.append(train_mse)
    
    # Record the cross validation MSEs 
    yhat = model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    nn_cv_mses.append(cv_mse)

    
# print results
print("RESULTS:")
for model_num in range(len(nn_train_mses)):
    print(
        f"Model {model_num+1}: Training MSE: {nn_train_mses[model_num]:.2f}, " +
        f"CV MSE: {nn_cv_mses[model_num]:.2f}"
        )